### ISSUE TITLE
can not use in vue 2

### ISSUE THREAD

**Issue by binoysarker** [tpisto/pdf-fill-form#102]
Hello sir, i am trying to use this package in vue 2 (typescirpt + class component). I am getting this error 
![image](https://user-images.githubusercontent.com/26120595/125239594-b02f4c80-e30a-11eb-9454-3bb1c1c70590.png)
**My js file that i want to import and use**
![image](https://user-images.githubusercontent.com/26120595/125239882-20d66900-e30b-11eb-84e7-1a08b8438ca7.png)
**i have installed these packages.**
"pdf-fill-form": "^5.1.0",
"@types/pdf-fill-form": "^5.0.1",
Now my question is that how can i solve this ? 
Thanks.

**Comment by tpisto** [comment]
Hi! This library works only on Node.js environment. Browsers are not yet supported.
