### ISSUE TITLE
Support radio buttons

### ISSUE THREAD

**Issue by kmcnellis** [tpisto/pdf-fill-form#18]

**Comment by werty1001** [comment]
I need this also to

**Comment by mttchrry** [comment]
This would be huge for me.

**Comment by mttchrry** [comment]
I have a pull request for this currently, if anyone needs it immediately, find it at https://github.com/mttchrry/pdf-fill-form

**Comment by tpisto** [comment]
Thank you @mttchrry for your great contribution! I have now published v3.2.0 to npm.

**Comment by mttchrry** [comment]
Hey you are quite welcome, but I made a mistake, so sorry. I was cleaning
up some log stuff before my push and left and extra "}" in there that is
breaking the install, please merge my latest pull ASAP!
