### ISSUE TITLE
Qt4 unsupported, possible to upgrade to Qt5

### ISSUE THREAD

**Issue by bcgilkey32001** [tpisto/pdf-fill-form#19]
Qt4 has been deprecated in macOS Sierra. Sierra only supports qt5.

**Comment by AckerApple** [comment]
I tried installing qt5, [based on this StackOverflow](http://stackoverflow.com/questions/39690404/brew-install-qt-does-not-work-on-macos-sierra), and got a new error:

```
Package poppler-qt4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `poppler-qt4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'poppler-qt4' found
Package QtCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtCore' found
gyp: Call to 'pkg-config --cflags cairo poppler-qt4 QtCore' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

Hoping to see action on this. Thank you kindly

**Comment by robdvr** [comment]
Have you tried cloning down my pull request?

**Comment by AckerApple** [comment]
Thanks for pointing out your pull request @robdvr! I will try it out for sure today. Thanks good guy

**Comment by tpisto** [comment]
Merged the pull request by @robdvr. Thank you for your great contribution! Will update the NPM module also soon.

**Comment by AckerApple** [comment]
@robdvr, what an excellent contribution fer dang sure!! Extra exclamations!!!

My favorite part was having the OSX install fail on me and then seeing you added docs to repoint the installs and then everything worked AND FINALLY FINALLY FINALLY able to read the governments i-9 acroforms.

Thats one more for open source

**Comment by AckerApple** [comment]
Friendly reminder, please push update to npm

**Comment by robdvr** [comment]
@AckerApple Glad it worked!!
@tpisto of course! Thank you for all your work on this library.
