### ISSUE TITLE
Memory leak after generation file

### ISSUE THREAD

**Issue by vitstol** [tpisto/pdf-fill-form#25]
My application runs continuously. It generates one file per session. But there is a problem that after each application consumes more and more memory. That is, a memory leak occurs after file generation. 
p.s.  If you do not create the file during the session - no leaks. It occurs only after the generation.

**Comment by vhain** [comment]
Created PR: https://github.com/tpisto/pdf-fill-form/pull/27

**Comment by tpisto** [comment]
Please reopen the issue if it still happens with v3.2.0.
