### ISSUE TITLE
Digital/Electronic Signatures

### ISSUE THREAD

**Issue by sandman45** [tpisto/pdf-fill-form#26]
This is an excellent library!  Just used it and it works great.. 

I would like to have this library handle filling in the digital/electronic signatures fields as well.

I ended up using a workaround by converting to html adding signature then converting back to PDF

anyway thanks again!!  also this isnt really an issue but just a request.. couldnt find a spot to do that.

**Comment by lobabob** [comment]
You could use https://www.npmjs.com/package/nopodofo. This lib already returns a buffer after write, and that can be passed directly into nopodofo to sign it. An example for that can be seen here: https://corymickelson.github.io/NoPoDoFo/documentation/cookbook/signer.html
