### ISSUE TITLE
Support for node 0.10.x ?

### ISSUE THREAD

**Issue by Chun-Yang** [tpisto/pdf-fill-form#3]
I know it is not likely that you would support node 1.10.x. Nevertheless, can you give me some hints on how to support node 0.10.x?

I would like to contribute and maintain another branch.

**Comment by Chun-Yang** [comment]
I forked your repo and create a package for 1.10.x
https://github.com/Chun-Yang/pdf-fill-form

Thank you for sharing!

**Comment by tpisto** [comment]
Very good - I have build this module on top of NAN, so it should support multiple node versions with small changes. When you get it up and running with node 1.10.x pls submit the pull request.

**Comment by Chun-Yang** [comment]
I did get 1.10.32 running. I do want to submit a PR. However, the problem is 1.10.x and 1.12.x are not ABI compatible. I do not see a way to make both versions work under one npm package. Please tell me if you know a way to do that.

Andy way, I created a PR, you can decide what to do.

https://github.com/tpisto/pdf-fill-form/pull/5
