### ISSUE TITLE
Produce non-form pdf

### ISSUE THREAD

**Issue by andreas-gruenbacher** [tpisto/pdf-fill-form#30]
I'd be interested in using pdf-fill-form for filling out a form and then saving the result as a regular, non-form pdf. The result would be the same as filling out the form by hand and then printing to a file. Converting to an image is much too heavyweight.

**Comment by johnbenz13** [comment]
Any update on this? 
thanks

**Comment by tpisto** [comment]
Thank you for your interest for this library! The pdf-fill-form is based on the popular poppler pdf -library. For saving the form we use the poppler PDFConverter (https://people.freedesktop.org/~aacid/docs/qt5/classPoppler_1_1PDFConverter.html). Currently i'm not aware of it being able to convert forms to normal text. To have this feature we have 2 options:

1. We can contribute to poppler library this feature for the converter. I think this would be best, but hardest solution cause usually those libraries want then support all the possible cases.

2. We could try to utilize poppler to remove all the form fields from the pdf and replace then with TextBox elements. Input fields -> TextBox with the input field text. Multiselect -> TextBox with the selected text. Checkbox -> TextBox with "X" / "O" symbol.

For the actual implementation of any of these solutions I would need help from the community.

**Comment by andreas-gruenbacher** [comment]
If I understand correctly, cairo already supports PDF surfaces, so the existing page rendering code might mostly work for rendering to "plain" PDF already.

(In createImgPdf, I see that the page size is hardcoded to A4. That seems wrong; the output page size should probably be based on the input page size so that different page sizes and orientations will automatically work.)

**Comment by tpisto** [comment]
Closing this issue - this is now discussed more at #74
