### ISSUE TITLE
How do i pass an array of fields?

### ISSUE THREAD

**Issue by ratacibernetica** [tpisto/pdf-fill-form#33]
Maybe this is silly, but i can´t pass an **array of filled fields** when writing the pdf with the `.write` functions.

I've tried doing this:

```
pdfFillForm.writeSync('someFile.pdf', [ { 'nameField': 'value' }, { 'nameField2': 'value2' } ], { 'save': 'pdf' });
```

Any tips?

Awesome library, btw!

**Comment by tpisto** [comment]
I propose you to rethink your data structure. But if you necessarily want to have array of single value objects, then one way could be to use lodash:
npm install lodash
***
_ = require('lodash');
var myFields = [ { 'nameField': 'value' }, { 'nameField2': 'value2' } ]
var fillFields = _.reduce(myFields, function(myObj, value) {
   myObj[_.keys(value)[0]] = _.values(value)[0];
   return myObj;
}, {});
pdfFillForm.writeSync('someFile.pdf', fillFields, { 'save': 'pdf' });

This is just one quick untested solution, but hopefully gives you some ideas.

**Comment by ratacibernetica** [comment]
silly me, of course! one should pass a single object like
`{ 'field1': 'value1', 'field2: 'value2'  }` and so on...
