### ISSUE TITLE
Build fails at node-gyp rebuild.

### ISSUE THREAD

**Issue by TheNew000** [tpisto/pdf-fill-form#38]
I'm trying to install in a Docker container and am receiving this error message regardless of anything I tried.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.2.2 | linux | x64
gyp http GET https://nodejs.org/download/release/v6.2.2/node-v6.2.2-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
gyp ERR! System Linux 4.9.13-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebu
ild"
gyp ERR! cwd /app/node_modules/pdf-fill-form
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm info lifecycle pdf-fill-form@3.1.0~install: Failed to exec install script
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.9.13-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pdf-fill-form@3.1.0"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! pdf-fill-form@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdf-fill-form@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pdf-fill-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pdf-fill-form
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pdf-fill-form
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

#####THE npm-debug.log reads:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'pdf-fill-form' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose config Skipping project config: /app/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData pdf-fill-form
9 silly fetchNamedPackageData pdf-fill-form
10 silly mapToRegistry name pdf-fill-form
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://ct-avs-web.es.ad.adp.com:4873/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'pdf-fill-form',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   name: 'pdf-fill-form',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri http://ct-avs-web.es.ad.adp.com:4873/pdf-fill-form
15 verbose request uri http://ct-avs-web.es.ad.adp.com:4873/pdf-fill-form
16 verbose request no auth needed
17 info attempt registry request try #1 at 6:36:17 AM
18 verbose request id 5e3f134d3638d64a
19 verbose etag "8696401a0e3fda649919bbdda1edc8bf"
20 http request GET http://ct-avs-web.es.ad.adp.com:4873/pdf-fill-form
21 http 200 http://ct-avs-web.es.ad.adp.com:4873/pdf-fill-form
22 verbose headers { 'x-powered-by': 'verdaccio/2.0.1',
22 verbose headers   'content-type': 'application/json; charset=utf-8',

**Comment by TheNew000** [comment]
For anyone else having Docker issues I added this to the Dockerfile to get the system dependencies installed:

RUN apt-get update &&\
		apt-get install -y --force-yes --no-install-recommends \
			apt-utils vim \
			libpoppler-qt5-dev libcairo2-dev
RUN ["apt-get", "clean"]

And later in the file ran:

RUN npm config set strict-ssl false
ENV NODE_TLS_REJECT_UNAUTHORIZED 0
RUN npm install pdf-fill-form --without-ssl --insecure
ENV NODE_TLS_REJECT_UNAUTHORIZED 1

**Comment by JeremyGranger** [comment]
Do you still have this Dockerfile?

**Comment by Mihailoff** [comment]
```
FROM node:14-slim

RUN apt-get update
RUN apt-get install -y build-essential libpoppler-qt5-dev libcairo2-dev
RUN apt-get clean

COPY index.js .

RUN npm install

CMD ["node", "index.js"]
```
