### ISSUE TITLE
Question, any recomendation to create PDFs forms aside of acrobat?

### ISSUE THREAD

**Issue by k1r0s** [tpisto/pdf-fill-form#54]
Thanks @tpisto for this library! 

I tried lots of programs to create a pdf form that is able to work with this, but none of them work, of course acrobat do work like a charm. 

Do you have any recomendations? im running ubuntu :)

thanks!

**Comment by jpetso** [comment]
I used LibreOffice last year to create a PDF with form fields, had to fiddle a bit with how to set the PDF (FDF?) names of the fields for use with pdftk but in the end it worked out pretty well.
