### ISSUE TITLE
Error During Installation on Ubuntu 15.04

### ISSUE THREAD

**Issue by thealexbaron** [tpisto/pdf-fill-form#6]
I'm getting `child_process: customFds option is deprecated, use stdio instead.` when I run npm install (I also tried -g and it gave me the same error)

Here's the full output:

	> pdf-fill-form@1.0.2 install /home/alexb/form-filler/node_modules/pdf-fill-form
	> node-gyp rebuild

	child_process: customFds option is deprecated, use stdio instead.
	make: Entering directory '/home/alexb/form-filler/node_modules/pdf-fill-form/build'
	  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
	../src/pdf-fill-form.cc: In function ‘void InitAll(v8::Handle<v8::Object>)’:
	../src/pdf-fill-form.cc:13:16: error: ‘NanNew’ was not declared in this scope
	   exports->Set(NanNew<String>("readSync"),
			^
	../src/pdf-fill-form.cc:13:29: error: expected primary-expression before ‘>’ token
	   exports->Set(NanNew<String>("readSync"),
				     ^
	../src/pdf-fill-form.cc:14:28: error: expected primary-expression before ‘>’ token
	     NanNew<FunctionTemplate>(ReadSync)->GetFunction());
				    ^
	../src/pdf-fill-form.cc:14:41: error: request for member ‘GetFunction’ in ‘ReadSync’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
	     NanNew<FunctionTemplate>(ReadSync)->GetFunction());
						 ^
	../src/pdf-fill-form.cc:16:29: error: expected primary-expression before ‘>’ token
	   exports->Set(NanNew<String>("writeSync"),
				     ^
	../src/pdf-fill-form.cc:17:28: error: expected primary-expression before ‘>’ token
	     NanNew<FunctionTemplate>(WriteSync)->GetFunction());
				    ^
	../src/pdf-fill-form.cc:17:42: error: request for member ‘GetFunction’ in ‘WriteSync’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
	     NanNew<FunctionTemplate>(WriteSync)->GetFunction());
						  ^
	../src/pdf-fill-form.cc:19:29: error: expected primary-expression before ‘>’ token
	   exports->Set(NanNew<String>("writeAsync"),
				     ^
	../src/pdf-fill-form.cc:20:28: error: expected primary-expression before ‘>’ token
	     NanNew<FunctionTemplate>(WriteAsync)->GetFunction());
				    ^
	../src/pdf-fill-form.cc:20:43: error: request for member ‘GetFunction’ in ‘WriteAsync’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
	     NanNew<FunctionTemplate>(WriteAsync)->GetFunction());
						   ^
	pdf_fill_form.target.mk:108: recipe for target 'Release/obj.target/pdf_fill_form/src/pdf-fill-form.o' failed
	make: *** [Release/obj.target/pdf_fill_form/src/pdf-fill-form.o] Error 1
	make: Leaving directory '/home/alexb/form-filler/node_modules/pdf-fill-form/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
	gyp ERR! System Linux 3.19.0-22-generic
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/alexb/form-filler/node_modules/pdf-fill-form
	gyp ERR! node -v v0.12.1
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok 
	npm ERR! Linux 3.19.0-22-generic
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pdf-fill-form" "--save"
	npm ERR! node v0.12.1
	npm ERR! npm  v2.5.1
	npm ERR! code ELIFECYCLE

	npm ERR! pdf-fill-form@1.0.2 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the pdf-fill-form@1.0.2 install script 'node-gyp rebuild'.
	npm ERR! This is most likely a problem with the pdf-fill-form package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls pdf-fill-form
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/alexb/form-filler/npm-debug.log

**Comment by thealexbaron** [comment]
This appears to be an issue with using a version of node that's too new (`0.12.1`). Downgraded to  `0.10.40` and was able to install successfully. I'll need to get the newer version working, though since I need the `--harmony` flag.

**Comment by tpisto** [comment]
Hi! I released new v2.0.0 with upgraded nan bindings. Please check if that fixes the problem.
