### ISSUE TITLE
Accept buffer instead of filename

### ISSUE THREAD

**Issue by lobabob** [tpisto/pdf-fill-form#65]
In several use cases, you already have the file loaded in memory. It doesn't make sense to save that to a tmp file and then load that into pdf-fill-form. It would be a lot more convenient if we could do something like:

```javascript
pdfFillForm.read(buffer)
// or
pdfFillForm.write(buffer, { field1: val, field2: val }, { save: 'pdf' })
```

**Comment by lobabob** [comment]
Nvm, looks like this was already brought up here #4 . Was it decided that this feature won't make it in?

**Comment by dfharmon** [comment]
I have a PR open on this feature: https://github.com/tpisto/pdf-fill-form/pull/71 .

**Comment by tpisto** [comment]
@dfharmon Thank you for your contribution!  🎉
