### ISSUE TITLE
Error installing dependencies on Mac

### ISSUE THREAD

**Issue by Vortec4800** [tpisto/pdf-fill-form#66]
When running this command: `brew install qt5 cairo poppler --with-qt5` I get the error:

`Error: invalid option: --with-qt5`

Is there a new version of something that doesn't like this flag? I'm not able to install the module without passing this, as the `npm install` complains about not being able to find the required frameworks.

**Comment by mhadad** [comment]
I'm having the same error as above

I'm on Mojave running Homebrew 2.1.0

**Comment by brittbinler** [comment]
Same for me, running Mojave 10.14.4 with Homebrew 2.1.2.

**Comment by brittbinler** [comment]
Update, these steps eventually worked for me:

```
brew rm poppler; brew install -s poppler
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
npm install pdf-fill-form```

**Comment by claucece** [comment]
Oh, nice, it helped here @brittbinler :)
