### ISSUE TITLE
Error installing on OSX 10.9.5 on Node 0.12.7

### ISSUE THREAD

**Issue by tyleriguchi** [tpisto/pdf-fill-form#7]
> pdf-fill-form@1.0.2 install /Users/tyleriguchi/makapen/nano-string-middleware/node_modules/pdf-fill-form
> node-gyp rebuild

  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
../src/pdf-fill-form.cc:13:16: error: use of undeclared identifier 'NanNew'
  exports->Set(NanNew<String>("readSync"),
               ^
../src/pdf-fill-form.cc:13:23: error: 'String' does not refer to a value
  exports->Set(NanNew<String>("readSync"),
                      ^
/Users/tyleriguchi/.node-gyp/0.12.7/deps/v8/include/v8.h:1599:17: note:
      declared here
class V8_EXPORT String : public Primitive {
                ^
../src/pdf-fill-form.cc:16:16: error: use of undeclared identifier 'NanNew'
  exports->Set(NanNew<String>("writeSync"),
               ^
../src/pdf-fill-form.cc:16:23: error: 'String' does not refer to a value
  exports->Set(NanNew<String>("writeSync"),
                      ^
/Users/tyleriguchi/.node-gyp/0.12.7/deps/v8/include/v8.h:1599:17: note:
      declared here
class V8_EXPORT String : public Primitive {
                ^
../src/pdf-fill-form.cc:19:16: error: use of undeclared identifier 'NanNew'
  exports->Set(NanNew<String>("writeAsync"),
               ^
../src/pdf-fill-form.cc:19:23: error: 'String' does not refer to a value
  exports->Set(NanNew<String>("writeAsync"),
                      ^
/Users/tyleriguchi/.node-gyp/0.12.7/deps/v8/include/v8.h:1599:17: note:
      declared here
class V8_EXPORT String : public Primitive {
                ^
6 errors generated.
make: *** [Release/obj.target/pdf_fill_form/src/pdf-fill-form.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tyleriguchi/makapen/nano-string-middleware/node_modules/pdf-fill-form
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! pdf-fill-form@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdf-fill-form@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pdf-fill-form package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pdf-fill-form
npm ERR! There is likely additional logging output above.

**Comment by tyleriguchi** [comment]
Opened a pull request #8 that fixes this issue.

**Comment by jspizziri** [comment]
@tpisto, #8 fixes this, this issue can be closed now.
