### ISSUE TITLE
Version 5.0.0 doesn't compile

### ISSUE THREAD

**Issue by thehappycoder** [tpisto/pdf-fill-form#79]
Nodejs version: 10

```
../src/NodePoppler.cc:273:58: error: no matching function for call to 'v8::Value::BooleanValue(v8::Isolate*&)'
       antialiasing = antialiasParam->BooleanValue(isolate);
```

Switched back to previous version for now.

**Comment by dfharmon** [comment]
I have a PR around this issue -- https://github.com/tpisto/pdf-fill-form/pull/80

**Comment by florianbepunkt** [comment]
my bad, sorry for the troubles. I ported this to node 13 without testing different node versions as (noted this in the PR)

**Comment by tpisto** [comment]
@dfharmon Thank you for your PR
