### ISSUE TITLE
Instructions for Mac should be updated

### ISSUE THREAD

**Issue by mobileben** [tpisto/pdf-fill-form#87]
As indicated in #66, the standard instructions for installing with `brew` don't work. 

The sequence I did was:

```
brew install -s poppler
export LDFLAGS=-L/usr/local/opt/qt5/lib
export CPPFLAGS=-I/usr/local/opt/qt5/include
export PKG_CONFIG_PATH=/usr/local/opt/qt5/lib/pkgconfig
```

#66 only did `PKG_CONFIG_PATH`, so maybe that is all that is needed.

Would probably be helpful for others if the instructions were updated.

**Comment by jybleau** [comment]
This is what I did on MacOS Catalina 10.15 and Homebrew 2.2.6.

The formulae are:
- Poppler 0.85 (which will install qt 5.14 as a dependency): [https://formulae.brew.sh/formula/poppler](https://formulae.brew.sh/formula/poppler)
- Cairo 1.16 [https://formulae.brew.sh/formula/cairo](https://formulae.brew.sh/formula/cairo)

Also seems like the first thing to do is to make sur xcode-select is installed.
```
xcode-select --install

# I did not use the "build from source option" (-s)
# All the development files are there too
brew install poppler cairo  

# qt5 folder is now named "qt" in the latest formula
export LDFLAGS=-L/usr/local/opt/qt/lib
export CPPFLAGS=-I/usr/local/opt/qt/include
export PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig
```

I suppose you may also append the "export" commands to your `~/.bash_profile` or `~/.zshrc` file for persistency...
