### ISSUE TITLE
File size increses 10 times when using imgpdf

### ISSUE THREAD

**Issue by alayor** [tpisto/pdf-fill-form#88]
The output file increases from 500KB to 10MB when I use the 'imgpdf'.
This doesn't happen with the 'pdf' option.
Is there any way to fix this?

**Comment by jybleau** [comment]
I'm starting to work with the library.

I guess it depends first on the complexity of your original PDF...

Did you try to change the scale (default to 0.2) factor and antialiasing (defaut false) properties? What optimisation could you get from it?

Scale factor defaul means 360dpi image per pages (72pdi / 0.2). It probably explains your situation. 
A scale of 0.72 would give you 100dpi.

**ref:**

[https://github.com/tpisto/pdf-fill-form/blob/master/src/NodePoppler.cc#L106](https://github.com/tpisto/pdf-fill-form/blob/master/src/NodePoppler.cc#L106)
[https://people.freedesktop.org/~aacid/docs/qt5/classPoppler_1_1Page.html#ae37d9b14a50231ed92260552964a1ed2](https://people.freedesktop.org/~aacid/docs/qt5/classPoppler_1_1Page.html#ae37d9b14a50231ed92260552964a1ed2)
